site_name: Crowdsec
nav:
  - Home: index.md
  - Crowdsec v0: '!include ./docs/v0.3.X/mkdocs.yml'
  - Crowdsec v1 : '!include ./docs/v1.X/mkdocs.yml'
  - Developers : https://crowdsecurity.github.io/api_doc/index.html?urls.primaryName=LAPI" target="_blank

markdown_extensions:
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - admonition
theme: 
  name: material
  logo: assets/images/crowdsec2.png
  favicon: assets/images/crowdsec2.png
  features:
    - navigation.tabs
  palette:
    primary: "#3d85c6" 
  language: en
  font:
    text: Montserrat
  highlightjs: true
  hljs_languages:
      - yaml
repo_url: https://github.com/crowdsecurity/crowdsec
repo_name: GitHub
plugins:
    - search
    - macros
    - monorepo
    - swagger
google_analytics:
    - UA-164365852-3
    - auto

extra:
    swagger_url: "https://raw.githubusercontent.com/crowdsecurity/crowdsec/wip_lapi/pkg/models/localapi_swagger.yaml"
    v0X:
      doc:
          new_issue: "[new documentation issue](https://github.com/crowdsecurity/crowdsec/issues/new)"
          discourse: "[CrowdSecurity discourse](http://discourse.crowdsec.net)"
          community: "[community](http://discourse.crowdsec.net)"
      hub:
          name: Crowdsec Hub
          htmlname: "[Crowdsec Hub](https://hub.crowdsec.net/)"
          url: "https://hub.crowdsec.net/"
          plugins_url: "https://hub.crowdsec.net/browse/#bouncers"
          scenarios_url: "https://hub.crowdsec.net/browse/#configurations"
          parsers_url: "https://hub.crowdsec.net/browse/#configurations"
          collections_url: "https://hub.crowdsec.net/browse/#collections"
      crowdsec:
          name: Crowdsec
          Name: Crowdsec
          bin: crowdsec-agent
          path: /usr/bin/crowdsec-agent
          url: https://github.com/crowdsecurity/crowdsec
          bugreport: "https://github.com/crowdsecurity/crowdsec/issues"
          main_log: "/var/log/crowdsec.log"
          download_url: https://github.com/crowdsecurity/crowdsec/releases/latest
      cli:
          name: cscli
          Name: Cscli
          bin: cscli
          path: /usr/bin/cscli
          main_doc: /Crowdsec/v0/cscli/cscli/
          url: "https://github.com/crowdsecurity/crowdsec"
          bugreport: "https://github.com/crowdsecurity/crowdsec/issues"
          api_doc: /Crowdsec/v0/cscli/cscli_api/
          ban_doc: /Crowdsec/v0/cscli/cscli_ban/
          metrics_doc: /Crowdsec/v0/cscli/cscli_metrics/
          remove_doc: /Crowdsec/v0/cscli/cscli_remove/
          install_doc: /Crowdsec/v0/cscli/cscli_install/
          list_doc: /Crowdsec/v0/cscli/cscli_list/
          update_doc: /Crowdsec/v0/cscli/cscli_update/
          upgrade_doc: /Crowdsec/v0/cscli/cscli_upgrade/
          backup_doc: /Crowdsec/v0/cscli/cscli_backup/
          simulation_doc: /Crowdsec/v0/cscli/cscli_simulation/
      config:
          cli_dir: /etc/crowdsec/cscli/
          crowdsec_dir: "/etc/crowdsec/config/"
          acquis_path: "/etc/crowdsec/config/acquis.yaml"
      bouncers:
          name: bouncers
          Name: bouncers
          url: "https://hub.crowdsec.net/browse/#bouncers"
          htmlname: "[bouncers](/Crowdsec/v0/bouncers/)"
          Htmlname: "[bouncers](/Crowdsec/v0/bouncers/)"
      plugins:
          name: backend plugins
          configpath: "/etc/crowdsec/plugins/backend/"
          binpath: "/usr/local/lib/crowdsec/plugins/"
      metabase:
          name: metabase
          url: https://github.com/crowdsecurity/crowdsec
      wizard:
          name: wizard
          url: "https://github.com/crowdsecurity/crowdsec"
          bin: "./wizard.sh"
          bugreport: "https://github.com/crowdsecurity/crowdsec/issues"
      ref:
          parser: "[parser](/Crowdsec/v0/references/parsers/)"
          Parser: "[Parser](/Crowdsec/v0/references/parsers/)"
          scenario: "[scenarios](/Crowdsec/v0/references/scenarios/)"
          Scenario: "[Scenarios](/Crowdsec/v0/references/scenarios/)"
          acquis: "[acquisition](/Crowdsec/v0/guide/crowdsec/acquisition/)"
          Acquis: "[Acquisition](/Crowdsec/v0/guide/crowdsec/acquisition/)"
          output: "[output](/Crowdsec/v0/references/output/)"
          Output: "[Output](/Crowdsec/v0/references/output/)"
  # All the technical terms
      event:
          name: event
          Name: Event
          htmlname: "[event](/Crowdsec/v0/getting_started/concepts/#event)"
          Htmlname: "[Event](/Crowdsec/v0/getting_started/concepts/#event)" 
      expr:
          name: expr
          Name: Expr
          htmlname: "[expr](/Crowdsec/v0/write_configurations/expressions/)"
          Htmlname: "[Expr](/Crowdsec/v0/write_configurations/expressions/)"
      filter:
          name: filter
          Name: Filter
          htmlname: "[filter](/Crowdsec/v0/references/parsers/#filter)"
          Htmlname: "[Filter](/Crowdsec/v0/references/parsers/#filter)"
      onsuccess:
          name: onsuccess
          Name: Onsuccess
          htmlname: "[onsuccess](/Crowdsec/v0/references/parsers/#onsuccess)"  
          Htmlname: "[Onsuccess](/Crowdsec/v0/references/parsers/#onsuccess)"  
      statics:
          name: statics
          Name: Statics
          htmlname: "[statics](/Crowdsec/v0/references/parsers/#statics)"
          Htmlname: "[Statics](/Crowdsec/v0/references/parsers/#statics)"
      parsers:
          name: parsers
          Name: Parsers
          htmlname: "[parsers](/Crowdsec/v0/getting_started/concepts/#parser)"
          Htmlname: "[Parsers](/Crowdsec/v0/getting_started/concepts/#parser)"
      scenarios:
          name: scenarios
          Name: Scenarios
          htmlname: "[scenarios](/Crowdsec/v0/getting_started/concepts/#scenario)"
          Htmlname: "[Scenarios](/Crowdsec/v0/getting_started/concepts/#scenario)"
      collections:
          name: collections
          Name: Collections
          htmlname: "[collections](/Crowdsec/v0/getting_started/concepts/#collections)"
          Htmlname: "[Collections](/Crowdsec/v0/getting_started/concepts/#collections)"
      timeMachine:
          name: timeMachine
          Name: TimeMachine
          htmlname: "[timeMachine](/Crowdsec/v0/getting_started/concepts/#timemachine)"
          Htmlname: "[TimeMachine](/Crowdsec/v0/getting_started/concepts/#timemachine)"
      overflow:
          name: overflow
          Name: Overflow
          htmlname: "[overflow](/Crowdsec/v0/getting_started/concepts/#overflow-or-signaloccurence)"
          Htmlname: "[Overflow](/Crowdsec/v0/getting_started/concepts/#overflow-or-signaloccurence)"
      whitelists:
          name: whitelists
          Name: Whitelists
          htmlname: "[whitelists](/Crowdsec/v0/write_configurations/whitelist/)"
          Htmlname: "[Whitelists](/Crowdsec/v0/write_configurations/whitelist/)"
      signal:
          name: signal
          Name: Signal
          htmlname: "[signal](/Crowdsec/v0/getting_started/concepts/#overflow-or-signaloccurence)"
          Htmlname: "[Signal](/Crowdsec/v0/getting_started/concepts/#overflow-or-signaloccurence)"
  #scenario stuff
      stage:
          name: stage
          Name: Stage
          htmlname: "[stage](/Crowdsec/v0/getting_started/concepts/#stages)"
          Htmlname: "[Stage](/Crowdsec/v0/getting_started/concepts/#stages)"
      leakspeed:
          name: leakspeed
          Name: Leakspeed
          htmlname: "[leakspeed](/Crowdsec/v0/references/scenarios/#leakspeed)"
          Htmlname: "[Leakspeed](/Crowdsec/v0/references/scenarios/#leakspeed)"
      capacity:
          name: capacity
          Name: Capacity
          htmlname: "[capacity](/Crowdsec/v0/references/scenarios/#capacity)"
          Htmlname: "[Capacity](/Crowdsec/v0/references/scenarios/#capacity)"
      duration:
          name: duration
          Name: Duration
          htmlname: "[duration](/Crowdsec/v0/references/scenarios/#duration)"
          Htmlname: "[Duration](/Crowdsec/v0/references/scenarios/#duration)"
      prometheus:
          name: prometheus
          htmlname: "[prometheus](https://github.com/prometheus/client_golang)"
      api:
          name: API
          htmlname: "[API](TBD)"
          topX:
              name: topX
              htmlname: "[topX](TBD)"
###############################################################
### Bellow are defines for V1 and later of the documentation ##
###############################################################
    v1X:
      doc:
          new_issue: "[new documentation issue](https://github.com/crowdsecurity/crowdsec/issues/new)"
          discourse: "[CrowdSecurity discourse](http://discourse.crowdsec.net)"
          community: "[community](http://discourse.crowdsec.net)"
      hub:
          name: Crowdsec Hub
          htmlname: "[Crowdsec Hub](https://hub.crowdsec.net/)"
          url: "https://hub.crowdsec.net/"
          plugins_url: "https://hub.crowdsec.net/browse/#bouncers"
          scenarios_url: "https://hub.crowdsec.net/browse/#configurations"
          parsers_url: "https://hub.crowdsec.net/browse/#configurations"
          collections_url: "https://hub.crowdsec.net/browse/#collections"
      crowdsec:
          name: crowdsec-agent
          Name: Crowdsec-agent
          bin: crowdsec
          path: /usr/local/bin/crowdsec
          url: https://github.com/crowdsecurity/crowdsec
          bugreport: "https://github.com/crowdsecurity/crowdsec/issues"
          main_log: "/var/log/crowdsec.log"
          download_url: https://github.com/crowdsecurity/crowdsec/releases/latest
      lapi:
          name: local API (LAPI)
          Name: Local API (LAPI)
          htmlName: "[local api](/Crowdsec/v1/localAPI/)"
          htmlname: "[local API](/Crowdsec/v1/localAPI/)"
      cli:
          name: cscli
          Name: Cscli
          bin: cscli
          path: /usr/bin/cscli
          main_doc: /Crowdsec/v1/cscli/cscli/
          url: "https://github.com/crowdsecurity/crowdsec"
          bugreport: "https://github.com/crowdsecurity/crowdsec/issues"
          api_doc: /Crowdsec/v1/cscli/cscli_api/
          ban_doc: /Crowdsec/v1/cscli/cscli_ban/
          metrics_doc: /Crowdsec/v1/cscli/cscli_metrics/
          remove_doc: /Crowdsec/v1/cscli/cscli_remove/
          install_doc: /Crowdsec/v1/cscli/cscli_install/
          list_doc: /Crowdsec/v1/cscli/cscli_list/
          update_doc: /Crowdsec/v1/cscli/cscli_update/
          upgrade_doc: /Crowdsec/v1/cscli/cscli_upgrade/
          backup_doc: /Crowdsec/v1/cscli/cscli_backup/
          simulation_doc: /Crowdsec/v1/cscli/cscli_simulation/
      config:
          cli_dir: /etc/crowdsec/cscli/
          crowdsec_dir: "/etc/crowdsec/config/"
          acquis_path: "/etc/crowdsec/config/acquis.yaml"
      bouncers:
          name: bouncers
          Name: Bouncers
          url: "https://hub.crowdsec.net/browse/#bouncers"
          htmlname: "[bouncers](/Crowdsec/v1/bouncers/)"
          Htmlname: "[bouncers](/Crowdsec/v1/bouncers/)"
      plugins:
          name: backend plugins
          configpath: "/etc/crowdsec/plugins/backend/"
          binpath: "/usr/local/lib/crowdsec/plugins/"
      metabase:
          name: metabase
          url: https://github.com/crowdsecurity/crowdsec
          htmlName: "[dashboard](/Crowdsec/v1/observability/dashboard)"
      wizard:
          name: wizard
          url: "https://github.com/crowdsecurity/crowdsec"
          bin: "./wizard.sh"
          bugreport: "https://github.com/crowdsecurity/crowdsec/issues"
      ref:
          parser: "[parser](/Crowdsec/v1/references/parsers/)"
          Parser: "[Parser](/Crowdsec/v1/references/parsers/)"
          scenario: "[scenarios](/Crowdsec/v1/references/scenarios/)"
          Scenario: "[Scenarios](/Crowdsec/v1/references/scenarios/)"
          acquis: "[acquisition](/Crowdsec/v1/guide/crowdsec/acquisition/)"
          Acquis: "[Acquisition](/Crowdsec/v1/guide/crowdsec/acquisition/)"
          output: "[output](/Crowdsec/v1/references/output/)"
          Output: "[Output](/Crowdsec/v1/references/output/)"
  # All the technical terms
      event:
          name: event
          Name: Event
          htmlname: "[event](/Crowdsec/v1/getting_started/concepts/#event)"
          Htmlname: "[Event](/Crowdsec/v1/getting_started/concepts/#event)" 
      expr:
          name: expr
          Name: Expr
          htmlname: "[expr](/Crowdsec/v1/write_configurations/expressions/)"
          Htmlname: "[Expr](/Crowdsec/v1/write_configurations/expressions/)"
      filter:
          name: filter
          Name: Filter
          htmlname: "[filter](/Crowdsec/v1/references/parsers/#filter)"
          Htmlname: "[Filter](/Crowdsec/v1/references/parsers/#filter)"
      onsuccess:
          name: onsuccess
          Name: Onsuccess
          htmlname: "[onsuccess](/Crowdsec/v1/references/parsers/#onsuccess)"  
          Htmlname: "[Onsuccess](/Crowdsec/v1/references/parsers/#onsuccess)"  
      statics:
          name: statics
          Name: Statics
          htmlname: "[statics](/Crowdsec/v1/references/parsers/#statics)"
          Htmlname: "[Statics](/Crowdsec/v1/references/parsers/#statics)"
      parsers:
          name: parsers
          Name: Parsers
          htmlname: "[parsers](/Crowdsec/v1/getting_started/concepts/#parser)"
          Htmlname: "[Parsers](/Crowdsec/v1/getting_started/concepts/#parser)"
      scenarios:
          name: scenarios
          Name: Scenarios
          htmlname: "[scenarios](/Crowdsec/v1/getting_started/concepts/#scenario)"
          Htmlname: "[Scenarios](/Crowdsec/v1/getting_started/concepts/#scenario)"
      collections:
          name: collections
          Name: Collections
          htmlname: "[collections](/Crowdsec/v1/getting_started/concepts/#collections)"
          Htmlname: "[Collections](/Crowdsec/v1/getting_started/concepts/#collections)"
      timeMachine:
          name: timeMachine
          Name: TimeMachine
          htmlname: "[timeMachine](/Crowdsec/v1/getting_started/concepts/#timemachine)"
          Htmlname: "[TimeMachine](/Crowdsec/v1/getting_started/concepts/#timemachine)"
      alert:
          name: alert
          Name: Alert
          htmlname: "[alert](/Crowdsec/v1/getting_started/concepts/#alert)"
          Htmlname: "[Alert](/Crowdsec/v1/getting_started/concepts/#alert)"
      decision:
          name: decision
          Name: Decision
          htmlname: "[decision](/Crowdsec/v1/getting_started/concepts/#decision)"
          Htmlname: "[Decision](/Crowdsec/v1/getting_started/concepts/#decision)"
    #   overflow:
    #       name: overflow
    #       Name: Overflow
    #       htmlname: "[overflow](/Crowdsec/v1/getting_started/concepts/#overflow-or-signaloccurence)"
    #       Htmlname: "[Overflow](/Crowdsec/v1/getting_started/concepts/#overflow-or-signaloccurence)"
      whitelists:
          name: whitelists
          Name: Whitelists
          htmlname: "[whitelists](/Crowdsec/v1/write_configurations/whitelist/)"
          Htmlname: "[Whitelists](/Crowdsec/v1/write_configurations/whitelist/)"
    #   signal:
    #       name: signal
    #       Name: Signal
    #       htmlname: "[signal](/Crowdsec/v1/getting_started/concepts/#overflow-or-signaloccurence)"
    #       Htmlname: "[Signal](/Crowdsec/v1/getting_started/concepts/#overflow-or-signaloccurence)"
  #scenario stuff
      stage:
          name: stage
          Name: Stage
          htmlname: "[stage](/Crowdsec/v1/getting_started/concepts/#stages)"
          Htmlname: "[Stage](/Crowdsec/v1/getting_started/concepts/#stages)"
      leakspeed:
          name: leakspeed
          Name: Leakspeed
          htmlname: "[leakspeed](/Crowdsec/v1/references/scenarios/#leakspeed)"
          Htmlname: "[Leakspeed](/Crowdsec/v1/references/scenarios/#leakspeed)"
      capacity:
          name: capacity
          Name: Capacity
          htmlname: "[capacity](/Crowdsec/v1/references/scenarios/#capacity)"
          Htmlname: "[Capacity](/Crowdsec/v1/references/scenarios/#capacity)"
      duration:
          name: duration
          Name: Duration
          htmlname: "[duration](/Crowdsec/v1/references/scenarios/#duration)"
          Htmlname: "[Duration](/Crowdsec/v1/references/scenarios/#duration)"
      prometheus:
          name: prometheus
          htmlname: "[prometheus](https://github.com/prometheus/client_golang)"
      api:
          name: API
          htmlname: "[API](TBD)"
          topX:
              name: topX
              htmlname: "[topX](TBD)"

