site_name: Crowdsec/v1
nav:
  - Home: index.md
  - Getting Started:
#    - Glossary: getting_started/glossary.md
    - Concepts : getting_started/concepts.md
    - Install Crowdsec : getting_started/installation.md
    - Upgrade Crowdsec: getting_started/upgrades.md
    - Crowdsec Tour: getting_started/crowdsec-tour.md
  - User guide:
    - CLI: user_guide/cscli.md
    - Config management:
      - Collections: user_guide/configurations_management/collections.md
      - Parsers: user_guide/configurations_management/parsers.md
      - Enrichers: user_guide/configurations_management/enrichers.md
      - Scenarios: user_guide/configurations_management/scenarios.md
    - Decisions management: user_guide/decision_management.md
    - Bouncers & machines management: user_guide/bouncer_machine_management.md
    - Data sources config: 
       - Introduction: user_guide/data_sources/acquisition.md
       - Files: user_guide/data_sources/file.md
       - Journalctl: user_guide/data_sources/journalctl.md
       - Cloudwatch: user_guide/data_sources/cloudwatch.md
       - Syslog: user_guide/data_sources/syslog.md
    - Databases: user_guide/database.md
    - Network management: user_guide/network.md
    - Simulation management: user_guide/simulation_mode.md
    - Crowdsec forensic mode: user_guide/forensic_mode.md
    - Debugging: user_guide/debugging_configs.md
  - CLI:
    - Cscli: cscli/cscli.md
    - Alerts: cscli/cscli_alerts.md
    - Bouncers: cscli/cscli_bouncers.md
    - Collections: cscli/cscli_collections.md
    - Completion: cscli/cscli_completion.md
    - Config: cscli/cscli_config.md
    - Dashboard: cscli/cscli_dashboard.md
    - Decisions: cscli/cscli_decisions.md
    - Hub: cscli/cscli_hub.md
    - Machines: cscli/cscli_machines.md
    - Metrics: cscli/cscli_metrics.md
    - Parsers: cscli/cscli_parsers.md
    - Postoverflows: cscli/cscli_postoverflows.md
    - Scenarios: cscli/cscli_scenarios.md
    - Simulation: cscli/cscli_simulation.md
  - Local API: 
    - Introduction: localAPI/index.md
    - API Guide: localAPI/howto.md
    - Swagger: https://crowdsecurity.github.io/api_doc/index.html?urls.primaryName=LAPI" target="_blank
  - Observability:
    - Overview: observability/overview.md
    - Logs: observability/logs.md
    - Metrics: 
        - Prometheus: observability/prometheus.md
        - Command line: observability/command_line.md
    - Dashboard: observability/dashboard.md
  - Bouncers: bouncers/index.md
  - References:
    - Parsers, Scenarios etc.:
      - Stages format: references/stages.md
      - Parsers format: references/parsers.md
      - Scenarios format: references/scenarios.md
      - PostOverlows format: references/postoverflows.md
      - Enrichers format: references/enrichers.md
      - Collections format: references/collections.md
      - Expressions helpers: references/expressions.md
      - Patterns references: references/patterns-documentation.md
    - Configuration files:
      - Configuration format: references/crowdsec-config.md
      - Database format: references/database.md
      - Acquisition format: references/acquisition.md
      - Profiles format: references/profiles.md
      - Simulation configuration: references/simulation.md
    - Runtime objects:
      - Event object: references/events.md
      - Alert object: references/alerts.md
      - Decision object: references/decisions.md
  - Write Configurations:
    - Requirements: write_configurations/requirements.md
    - Acquisition: write_configurations/acquisition.md
    - Parsers: write_configurations/parsers.md
    - Scenarios: write_configurations/scenarios.md
    - Whitelists: write_configurations/whitelist.md
  - Upgrade V0.X to V1.X: migration.md

