site_name: Crowdsec/v0
nav:
  - Home: index.md
  - Getting Started:
    - Concepts & Glossary : getting_started/concepts.md
    - Install Crowdsec : getting_started/installation.md
    - Crowdsec Tour: getting_started/crowdsec-tour.md
  - Guide:
    - Overview: guide/crowdsec/overview.md
    - Acquisition: guide/crowdsec/acquisition.md
    - Parsers: guide/crowdsec/parsers.md
    - Enrichers: guide/crowdsec/enrichers.md
    - Scenarios: guide/crowdsec/scenarios.md
    - Cscli: guide/cscli.md
    - Simulation Mode: guide/crowdsec/simulation.md
  - Cheat Sheets:
    - Ban Management: cheat_sheets/ban-mgmt.md
    - Configuration Management: cheat_sheets/config-mgmt.md
    - Debugging Parsers & Scenarios: cheat_sheets/debugging_configs.md
  - Observability:
    - Overview: observability/overview.md
    - Logs: observability/logs.md
    - Metrics: 
        - Prometheus: observability/prometheus.md
        - Command line: observability/command_line.md
    - Dashboard: observability/dashboard.md
  - References:
    - Parsers format: references/parsers.md
    - Scenarios format: references/scenarios.md
    - Outputs format: references/output.md
  - Write Configurations:
    - Requirements: write_configurations/requirements.md
    - Acquisition: write_configurations/acquisition.md
    - Parsers: write_configurations/parsers.md
    - Scenarios: write_configurations/scenarios.md
    - Whitelists: write_configurations/whitelist.md
    - Expressions: write_configurations/expressions.md
  - bouncers: bouncers/index.md
  - Contributing: 
    - Writing Output Plugins: references/plugins_api.md
  - Cscli commands:
    - Cscli: cscli/cscli.md
    - API: cscli/cscli_api.md
    - Backup: cscli/cscli_backup.md
    - Bans: cscli/cscli_ban.md
    - Metrics: cscli/cscli_metrics.md
    - Update: cscli/cscli_update.md
    - Install configurations: cscli/cscli_install.md
    - Remove configurations: cscli/cscli_remove.md
    - Upgrade configurations: cscli/cscli_upgrade.md
    - List configurations: cscli/cscli_list.md
    - Inspect configurations: cscli/cscli_inspect.md
    - Manage simulation: cscli/cscli_simulation.md
    - Dashboard: cscli/cscli_dashboard.md
  - Upgrade V0.X to V1.X: migration.md
