name: Tests

# Main workflow for tests, it calls all the others through parallel jobs.
#
# A final step collects and merges coverage output, then pushes it to
# coveralls.io
#
# https://docs.github.com/en/actions/using-workflows/reusing-workflows

on:
  push:
    branches:
      - master
      - testing*
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - master
      - testing*
    paths-ignore:
      - 'README.md'

jobs:

  go-tests:
    uses: ./.github/workflows/go-tests.yml

  bats-sqlite:
    uses: ./.github/workflows/bats-sqlite-coverage.yml

  # Jobs for Postgres and MySQL can have failing tests on GitHub CI, but they
  # pass when run on devs' machines or in the release checks. We disable them
  # here by default. Remove the if..false to enable them.

  bats-mariadb:
    uses: ./.github/workflows/bats-mysql.yml
    with:
      database_image: mariadb:latest
    secrets:
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD}}

  bats-mysql:
    uses: ./.github/workflows/bats-mysql.yml
    with:
      database_image: mysql:latest
    secrets:
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD}}

  bats-postgres:
    if: ${{ false }}
    uses: ./.github/workflows/bats-postgres.yml
    secrets:
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD}}

  bats-hub:
    uses: ./.github/workflows/bats-hub.yml
    secrets:
      GIST_BADGES_ID: ${{ secrets.GIST_BADGES_ID }}
      GIST_BADGES_SECRET: ${{ secrets.GIST_BADGES_SECRET }}

