name: Dispatch to hub when creating pre-release

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master

jobs:
  dispatch:
    name: dispatch to hub-tests
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        if: ${{ github.repository_owner == 'crowdsecurity' }}
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          event-type: trigger_ci_hub
          repository: crowdsecurity/hub
          client-payload: '{"version": "${{ steps.keydb.outputs.release }}"}'
